const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Two Podfile fixes react-native-firebase needs under this project's
// (static-linkage, non-`use_frameworks!`) CocoaPods setup — `ios/` is
// gitignored and regenerated by every `expo prebuild`/`expo run:ios`, so
// both have to be a config plugin rather than one-off Podfile edits:
//
// 1. @react-native-firebase/app (v20+) resolves Firebase via Swift Package
//    Manager by default. This Podfile never sets `use_frameworks!` (no
//    `ios.useFrameworks` in Podfile.properties.json, no `expo-build-
//    properties` plugin), so `pod install` defaults to static linkage
//    overall — which collides with Firebase's SPM packages (each RNFB pod
//    embeds its own copy, causing duplicate-symbol errors at link time).
//    RNFB's own firebase_spm.rb documents the fix: set
//    `$RNFirebaseDisableSPM = true` before the target block, falling back
//    to the legacy CocoaPods-resolved Firebase SDK instead of SPM.
// 2. With SPM disabled, Firebase resolves via CocoaPods instead — but
//    GoogleUtilities (a FirebaseCoreInternal dependency) has no module map,
//    so Swift pods can't import it under static linkage unless modular
//    headers are turned on (`use_modular_headers!`) — RNFB's own
//    documented CocoaPods/non-SPM install requirement.
module.exports = function withRNFirebasePodfileFixes(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf-8');

      const spmMarker = '$RNFirebaseDisableSPM = true';
      if (!contents.includes(spmMarker)) {
        contents = `${spmMarker}\n${contents}`;
      }

      // With SPM disabled, Firebase resolves via CocoaPods instead — but
      // under this project's static linkage, GoogleUtilities (a
      // FirebaseCoreInternal dependency) has no module map, so Swift pods
      // can't import it unless modular headers are turned on. This is
      // react-native-firebase's own documented CocoaPods (non-SPM) install
      // requirement, not specific to this project.
      if (!contents.includes('use_modular_headers!')) {
        contents = contents.replace('use_expo_modules!', 'use_modular_headers!\n  use_expo_modules!');
      }

      fs.writeFileSync(podfilePath, contents);
      return config;
    },
  ]);
};
